@host = http://localhost:8000  

### Obtenir tous les utilisateurs (admin seulement)
GET {{host}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTk1NjljNzFjZTRlYzM5OTQwZTMxMWUiLCJpc19hZG1pbiI6dHJ1ZSwiZmlybV9uYW1lIjoiTWUgZ3VzdGEgcGFlbGxhIiwiaWF0IjoxNzA0ODAxOTc5LCJleHAiOjE3MDQ4ODgzNzl9.quP-zQXc4Nlx5PCkuaJ8sY_ZkJZqhESL4hcoooWFDxs


### Créer un nouvel utilisateur (admin seulement)
POST {{host}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTk1NjljNzFjZTRlYzM5OTQwZTMxMWUiLCJpc19hZG1pbiI6dHJ1ZSwiZmlybV9uYW1lIjoiTWUgZ3VzdGEgcGFlbGxhIiwiaWF0IjoxNzA0NzAxNjkyLCJleHAiOjE3MDQ3ODgwOTJ9.UNeklMTH9DwWSFOj237OTbeWARJzEM_ZgUyTEvS7Nz8
Content-Type: application/json

{
    "firm_name": "test2",
    "first_name": "Prénom",
    "last_name": "Nom de famille",
    "email": "email@exemple.com",
    "phone_number": "0102030405",
    "password": "bonjour"
}

### Obtenir un utilisateur spécifique par son nom d'entreprise
GET {{host}}/users/Toyota
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTk1NjljNzFjZTRlYzM5OTQwZTMxMWUiLCJpc19hZG1pbiI6dHJ1ZSwiZmlybV9uYW1lIjoiTWUgZ3VzdGEgcGFlbGxhIiwiaWF0IjoxNzA0NzAxNjkyLCJleHAiOjE3MDQ3ODgwOTJ9.UNeklMTH9DwWSFOj237OTbeWARJzEM_ZgUyTEvS7Nz8


### Mettre à jour un utilisateur spécifique par son nom d'entreprise (admin seulement)
PUT {{host}}/users/Antoine
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTk1NjljNzFjZTRlYzM5OTQwZTMxMWUiLCJpc19hZG1pbiI6dHJ1ZSwiZmlybV9uYW1lIjoiTWUgZ3VzdGEgcGFlbGxhIiwiaWF0IjoxNzA0NzAxNjkyLCJleHAiOjE3MDQ3ODgwOTJ9.UNeklMTH9DwWSFOj237OTbeWARJzEM_ZgUyTEvS7Nz8
Content-Type: application/json

{
    "first_name": "Teixeira de jésus",
    "last_name": "Axel"
}


### Supprimer un utilisateur spécifique par son nom d'entreprise (admin seulement)
DELETE {{host}}/users/test2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTk1NjljNzFjZTRlYzM5OTQwZTMxMWUiLCJpc19hZG1pbiI6dHJ1ZSwiZmlybV9uYW1lIjoiTWUgZ3VzdGEgcGFlbGxhIiwiaWF0IjoxNzA0NzAxNjkyLCJleHAiOjE3MDQ3ODgwOTJ9.UNeklMTH9DwWSFOj237OTbeWARJzEM_ZgUyTEvS7Nz8


### Authentifier un utilisateur et obtenir un token
POST {{host}}/login
Content-Type: application/json

{
    "firm_name": "Me gusta paella",
    "password": "Qwaser26"
}

### Accuser réception du courrier
POST {{host}}/users/Antoine/reception
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTk1OWM1MTM0ZGZhZmZkZTA5MDk3NGYiLCJpc19hZG1pbiI6ZmFsc2UsImZpcm1fbmFtZSI6IlRveW90YSIsImlhdCI6MTcwNDcxMTMyOCwiZXhwIjoxNzA0Nzk3NzI4fQ.u3gHQFWZORFYXjCZPXLICqMQdp-N3x1bRw6AHEGaiqs

### Notifier les utilisateurs d'un nouveau courrier (admin seulement)
POST {{host}}/notify_mail
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTk1NjljNzFjZTRlYzM5OTQwZTMxMWUiLCJpc19hZG1pbiI6dHJ1ZSwiZmlybV9uYW1lIjoiTWUgZ3VzdGEgcGFlbGxhIiwiaWF0IjoxNzA0NzAxNjkyLCJleHAiOjE3MDQ3ODgwOTJ9.UNeklMTH9DwWSFOj237OTbeWARJzEM_ZgUyTEvS7Nz8
Content-Type: application/json

{
    "firmsToNotify": ["Toyota"]
}

### deconexion
GET {{host}}/logout

